// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Dependent")>]
[<assembly: AssemblyProductAttribute("FSharp.Dependent")>]
[<assembly: AssemblyDescriptionAttribute("Simulates dependent types with type-level naturals and inline functions.")>]
[<assembly: AssemblyVersionAttribute("1.1.2983.2350")>]
[<assembly: AssemblyFileVersionAttribute("1.1.2983.2350")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Dependent"
    let [<Literal>] AssemblyProduct = "FSharp.Dependent"
    let [<Literal>] AssemblyDescription = "Simulates dependent types with type-level naturals and inline functions."
    let [<Literal>] AssemblyVersion = "1.1.2983.2350"
    let [<Literal>] AssemblyFileVersion = "1.1.2983.2350"
    let [<Literal>] AssemblyConfiguration = "Release"
